### ISSUE TITLE
Base Building Plan Icon not aligned

### ISSUE THREAD

**Issue by PotatoCombat** [nathantalewis/oni-scaffolds#3]
Hi! I've just started using the mod and am loving it!

Recent change seems to have cause the Base Icon to be misaligned though.

<img width="148" alt="Screenshot 2023-12-09 at 12 24 03 AM" src="https://github.com/nathantalewis/oni-scaffolds/assets/39809238/bff6e3cb-fe60-41f4-9e7b-fd97bac12ed7">

Issue seems to be fixed by always returning true in the below code snippet (Scaffolds_Patch.cs).
But could someone kindly verify please as I'm not familiar with ONI code 😄 .

```
        public static bool Prefix(BuildingDef __instance)
        {
          if (__instance.name == "Scaffold")
          {
            __instance.CraftRecipe = new Recipe(__instance.BuildingComplete.PrefabID().Name, 1f, (SimHashes)0, __instance.Name)
            {
              Icon = __instance.UISprite
            };
            Recipe.Ingredient item = new Recipe.Ingredient(__instance.MaterialCategory[0], -1); // sets the required amount to -1kg for the build menu
            __instance.CraftRecipe.Ingredients.Add(item);
          }
          return true;
        }
```

**Comment by nathantalewis** [comment]
Yipes! I think we might be able to make this a Postfix patch instead of a Prefix patch, which is generally recommended and should let the original Klei code do what it needs to do instead of skipping over it.

**Comment by nathantalewis** [comment]
Postfix didn't actually help. I reverted the change that was meant to allow a Scaffold to be placed when less than 1kg of buildable material was available.

Thank you for the quick bug report!

**Comment by nathantalewis** [comment]
@QikaHome, you had asked in Steam what the bug was after making the recipe require -1 kg. This is the bug.
