### ISSUE TITLE
Add a french translation

### ISSUE THREAD

**Issue by Pholith** [nathantalewis/oni-scaffolds#4]
Hi
Here's a french translation for the mod, the file should be named fr.po
[scaffol_fr.zip](https://github.com/nathantalewis/oni-scaffolds/files/13686912/scaffol_fr.zip)

**Comment by nathantalewis** [comment]
@Pholith, I just published a new version with this French translation. Can you test it and let me know if the file is where it needs to be?

**Comment by Pholith** [comment]
It's perfect, thanks ! @nathantalewis
